// Raritäten-Schwänze (implizit Gewicht 1) — von extract-tails.js erzeugt, danach kuratiert.
// Merge-Regel: Integration hängt first an mid+modern (bzw. flaches Array) und last an region r an.
const NAME_TAILS_BY_NATION = {
    GBR: [
        { r: 0, first: ["Michael","Daniel","Adam","Steve","Andy","Robert","Dave","Joe","Matthew","Matt","Luke","Kevin","Craig","Steven","Scott","Liam","Darren","Jason","Nick","Neil","Stuart","Rob","Colin","Thomas","Lewis"], last: ["Williams","Johnson","James","Hall","Harris","Scott","Clark","King","Moore","Turner","Ward","Morgan","Morris","Anderson","Campbell","Young","Harrison","Baker","Allen","Mitchell","Phillips","Davis","Miller","Parker","Price","Shaw","Simpson","Collins","Murray","Carter","Richardson","Cook","Bailey","Gray","Griffiths","Adams","Graham","Richards","Louise","Ellis","Cox","Foster","Rose","Robertson","Wilkinson","Russell","Mason","Reid","Matthews","Powell","Rogers","Gibson","Mills","Webb","Owen","Thomson","Holmes","Knight","Barnes","Harvey","Hunter","Stevens","Lloyd","Jenkins","Johnston","Fisher","Butler","Fox","Dixon","Grant","Ross","Pearson","Barker","Andrews","Bradley","Elliott","Kennedy","Reynolds","West","Henderson"] },
    ],
    GER: [
        { r: 0, first: ["Daniel","Peter","Jens","Jan","Bernd","Kevin","Mario","Robert","Sascha","Christoph","Alex","Stephan","Steffen","Andre","Philipp","Ali","Marc","Nico","Rene","Torsten","Maik","Dominik","Heiko","Holger","Manuel"], last: ["Meier","Schmitz","Schulze","Hofmann","Schmitt","König","Peters","Maier","Kaiser","Herrmann","Köhler","Walter","Fuchs","Mayer","Scholz","Möller","Schmid","Schubert","Friedrich","Huber","Weiß","Lorenz","Franke","Engel","Winter","Günther","Hahn","Keller","Beck","Albrecht","Baumann","Sommer","Ludwig","Roth","Otto","Schumacher","Mueller","Schuster","Paul","Heinrich","Seidel","Hansen","Can","Kraus","Vogt","Graf","Böhm","Schreiber","Voigt","Jäger","Groß","Krämer","Dietrich","Bergmann","Wolff","Horn","Pohl","Jansen","Seifert","Kühn","Schulte","Franz","Lindner","Arnold","Maus","Busch","Haas","Beyer","Ernst","Schumann","Wenzel","Ziegler","Ritter","Petersen","Sauer","Jahn","Berg","Rose","Hermann","Pfeiffer"] },
    ],
    ITA: [
        { r: 0, first: ["Domenico","Mauro","Pietro","Gianluca","Pasquale","Gianni","Fabrizio","Enrico","Raffaele","Filippo","Luciano","Cristian","Massimiliano","Gaetano","Dario","Diego","Alex","Vito","Christian","Mirko","Carmine","Manuel","Ciro","Giancarlo","Marcello"], last: ["Bruno","Dangelo","Longo","Messina","Lombardo","Gentile","Parisi","Fiore","Bianco","Palumbo","De Rosa","Serra","Rinaldi","Giuseppe","Ferraro","Grasso","Caputo","Martino","Sorrentino","Barone","Carbone","Basile","Pellegrino","Sanna","Damico","De Santis","Romeo","Pagano","Orlando","Ruggiero","Testa","Mariani","De Angelis","Martinelli","Piras","Mauro","Rosa","Salvatore","Marini","Fusco","Marco","Ferri","Morelli","Francesco","Napoli","Dagostino","Stella","Catalano","Palmieri","De Simone","Garofalo","Farina","Calabrese","Galli","Mazza","Napolitano","Silvestri","Luca","Pinna","Cirillo","Marchetti","Battaglia","Pepe","Simone","Costanzo","Valente","Monti","Grimaldi","Pellegrini","Pace","Perrone","Melis","Monaco","Arena","Aiello","Volpe","Viola","Carta","Ferro","Guerra"] },
    ],
    FRA: [
        { r: 0, first: ["David","Thomas","Michel","Kevin","Christian","Daniel","Bruno","Quentin","Mathieu","Florian","Alexis","Marc","Alex","Damien","Arnaud","Frederic","Dominique","Sylvain","Jerome","Valentin","Jonathan","Mickael","Adrien","Fabrice"], last: ["Ben","Dupont","Nicolas","Legrand","Lambert","Pierre","Muller","Rousseau","Fontaine","Fernandez","Bonnet","Mathieu","Henry","Lucas","Duval","Gauthier","Philippe","Lefevre","Roussel","Faure","Gautier","Masson","Dumont","Meyer","Joly","Boyer","Rose","Dufour","Caron","Louis","Francois","Ndiaye","Arnaud","Meunier","Leroux","Guillaume","Roy","Brunet","Barbier","Vidal","Brun","Blanchard","Schmitt","Clement","Diaby","Noel","Dupuis","Lemoine","Gaillard","Leclerc","Giraud","Renaud","Lou","Charles","Gerard","Paul","Aubert","Rey","Carpentier","Alexandre","Diarra","Roche","Picard","Leclercq","Bourgeois","Fabre","Lacroix","Dumas","Lecomte","Bou","Hubert","Deschamps","Berger","Rolland","Cohen"] },
        { r: 1, first: ["Benjamin"], last: ["Toure","Coulibaly","Fofana","Benoit","Sow"] },
    ],
    USA: [
        { r: 0, first: ["Daniel","James","Alex","Mike","Robert","Jorge","Miguel","Joe","Jesus","Andrew","Richard","Paul","William","Victor","Manuel","Antonio","Jonathan","Joseph","Brandon","Matt","Steve","Angel","Mario","Francisco","Oscar"], last: ["Gonzalez","Perez","Sanchez","Ramirez","Flores","Torres","Cruz","Gomez","Diaz","Reyes","Morales","Ortiz","Ramos","Mendoza","Castillo","Gutierrez","Ruiz","Alvarez","Jimenez","Aguilar","Castro","Chavez","Romero","Singh","Herrera","Vasquez","Mendez","Moreno","Vargas","Medina","Guzman","Fernandez","King","Santos","Vazquez","Mejia","Alvarado","Silva","Salazar","Green","Soto","Scott","James","Gonzales","Contreras","Rojas","Wright","Khan","Estrada","Hill","Kim","Nelson","Guerrero","Ortega","Maldonado","Delgado","Rios","Adams","Vega","Garza","Sandoval","Santiago","Campbell","Luna","Acosta","Dominguez","Juarez","Espinoza","Molina","Baker","Valdez","Roberts","Cabrera","Edwards","Joseph","Ayala","Munoz","Rose","Evans","Fuentes","Miranda","Avila","Campos","Love","Stewart","Escobar","Figueroa","Shah","Rivas","Marquez"] },
    ],
    BRA: [
        { r: 0, first: ["Daniel","Leonardo","Junior","Alexandre","Fabio","Edson","Adriano","Alex","Marcio","Tiago","Douglas","Mateus","Victor","Henrique","Renato","Vitor","Samuel","Luis","Ronaldo","Robson","Jefferson","Jorge","Claudio","Igor","Manoel"], last: ["Da Silva","Gonçalves","Mendes","Marques","Dos Santos","Batista","Melo","Machado","Santana","Moreira","Moura","Ramos","Junior","Medeiros","Bezerra","Cristina","Borges","Morais","Barros","Brito","Monteiro","Pinheiro","Castro","Farias","Rosa","Dantas","Miranda","Cavalcante","Nogueira","Reis","Tavares","Campos","Silveira","Cruz","Leite","Viana","Garcia","Maia","Neto","Felipe","Filho","Xavier","De Souza","Aparecida","Sales","Queiroz","Macedo","Amorim","De Oliveira","Mello","Vasconcelos","Coelho","Siqueira","Cordeiro","Cunha","Azevedo","Aguiar","Albuquerque","Alencar","Pires","Felix","Matos","Lucas","Paula","Paiva","Menezes","Correia","Sampaio","Alexandre","Maciel","Augusto","Amaral","Torres","Neves","França","Braga","Roberto","Jesus","Freire","Antunes"] },
    ],
    JPN: [
        { r: 0, first: ["Takeshi","Masaki","Hiroaki","Kentaro","Marcelo","Kohei","Masato","Koichi","Roberto","Tomohiro","Ryota","Masayuki","Tetsuya","Yasuhiro","Yuya","Kenichi","Kazuhiro","Kei","Jorge","Shinya","Toru","Masashi","Yuichi","Tsuyoshi","Ryosuke"], last: ["Ono","Ishikawa","Aoki","Ishii","Sakai","Ueda","Hasegawa","Nakagawa","Nakano","Kondo","Fujii","Okamoto","Endo","Nishimura","Goto","Takeda","Arai","Takeuchi","Yamazaki","Miura","Fukuda","Tamura","Nakayama","Morita","Harada","Ota","Honda","Wada","Kikuchi","Kaneko","Miyamoto","Hara","Kojima","Miyazaki","Yokoyama","Shimada","Ishida","Shibata","Fujiwara","Masuda","Uchida","Ando","Fujimoto","Hirano","Higa","Ueno","Hirata","Hamada","Taniguchi","Matsui","Kawamura","Maruyama","Noguchi","Murata","Mizuno","Kinoshita","Nagai","Takagi","Kawai","Imai","Matsuo","Kubota","Koyama","Sakurai","Nagata","Takano","Iwasaki","Yamanaka","Yano","Kubo","Fukushima","Takada","Kawasaki","Sano","Uehara","Seki","Sugiyama","Yasuda","Nomura","Nishida"] },
    ],
    ESP: [
        { r: 0, first: ["Jesus","Jose Manuel","Juan Carlos","Victor","Miguel Angel","Javi","Roberto","Enrique","Eduardo","Andres","Fran","Dani","Ramon","Cristian","Juan Antonio","Francisco Javier","Ricardo","Rafa","Julio","Toni","Joan","Jose Maria","Santiago","Mohamed","Manolo"], last: ["Gutierrez","Morales","Ramirez","Castro","Blanco","Dominguez","Ortega","Ortiz","Delgado","Santos","Castillo","Medina","Rubio","Flores","Suarez","Marin","Cruz","Reyes","Sanz","Guerrero","Garrido","Garcia Garcia","Herrera","Lozano","Cortes","Iglesias","Vargas","Cabrera","Santana","Peña","Cano","Campos","Vega","Mendez","Gallego","Silva","Aguilar","Nuñez","Fuentes","Carrasco","Vidal","Caballero","Rojas","Prieto","Santiago","Montero","Mendoza","Mora","Hidalgo","Carmona","Nieto","Arias","Leon","Marquez","Lorenzo","Rivera","Soto","Calvo","Pascual","Gimenez","Heredia","Herrero","Vera","Gallardo","Madrid","Lara","Velasco","Rivas","Franco","Camacho","Bravo","Crespo","Parra","Espinosa","Pastor","Vicente","Salazar","Duran","Pardo","Montes"] },
    ],
    NED: [
        { r: 0, first: ["Peter","Hans","John","Martin","Rick","Kevin","Gerard","Mike","Michel","Frans","Nick","Niels","Roy","Michael","Danny"], last: ["Janssen","Jacobs","Vermeulen","De Bruin","Schouten","Van Den Heuvel","Van Der Veen","Van Beek","Van Den Broek","Verhoeven","Maas","Koster","Prins","Van Vliet","De Bruijn","Blom","Van Dam","Huisman","Van Der Heijden","Post","Peeters","Van Veen","Kuiper","Kramer","Boer","Veenstra","De Jonge","Scholten","Martens","Groen","Vink","Van Der Wal","Koning","Gerritsen","Postma","De Ruiter","Bosch","Jonker","Willemsen","Van Wijk","Timmermans","Evers","Van Den Brink","De Vos","Schipper","Van Loon","Smeets","Driessen","De Lange","Roos"] },
    ],
    BEL: [
        { r: 0, first: ["Patrick","Thomas","Mohamed","Michael","Daniel","Pascal","Julien","Jonathan","Guy","Ali","Eddy","Christian","Danny","Yves","Tim"], last: ["Ben","Janssen","Desmet","Devos","Lemmens","Dhondt","Dumont","Wauters","Smet","Vdb","Declercq","Leclercq","Petit","Mathieu","Timmermans","Cornelis","Baert","Lambrechts","Lauwers","Bertrand","Jansen","Bosmans","Christiaens","Lemaire","Pieters"] },
        { r: 1, first: [], last: ["Stevens","Hendrickx","De Clercq","Van Den Broeck","De Backer","Van De Velde","Coppens","Verhoeven","Cools","Thys","De Smedt","Lenaerts","De Wilde","De Cock","De Meyer","Verstraete","Vandenberghe","Verheyen","Geerts","De Ridder","De Pauw","Bogaert","Verbeke","Vermeiren","Van Den Bossche"] },
    ],
    SUI: [
        { r: 0, first: ["David","Christian","Antonio","Manuel","Marc","Kevin","Mario","Roland","Alex","Carlos","Fabian","Ali","Philippe","Rolf","Lukas"], last: ["Meyer","Zimmermann","Graf","Wyss","Berger","Roth","Baumgartner","Studer","Suter","Kaufmann","Bachmann","Bucher","Kunz","Hofer","Lehmann","Marti","Koch","Christen","Frey","Lüthi","Egli","Maurer","Schweizer","Gasser","Pfister","Wenger","Fuchs","Arnold","Koller","Bajrami","Kohler","Burri","Stalder","Schmidt","Wüthrich","Egger","Fernandez","Ramadani","Leuenberger","Furrer","Hug","Hofmann","Bieri","Tanner","Blaser","Wagner","Hess","Hunziker","Hauser","Vogel"] },
    ],
    AUT: [
        { r: 0, first: ["Daniel","Walter","Philipp","Herbert","Johannes","Jürgen","Matthias","Werner","Hannes","Sebastian","Marcel","Gerald","Rene","Alex","Georg"], last: ["Baumgartner","Wallner","Schmidt","Wolf","Auer","Wimmer","Ebner","Aigner","Haas","Binder","Koller","Holzer","Lehner","Schuster","Koch","Lackner","Graf","Wieser","Kaiser","Haider","Weiss","Strasser","Mair","König","Hauser","Krenn","Winter","Horvath","Kaufmann","Stadler","Kogler","Fink","Posch","Riegler","Karner","Rainer","Kern","Hackl","Maurer","Ortner","Fritz","Schwaiger","Resch","Seidl","Schober","Riedl","Neubauer","Strobl","Klein","Hofbauer"] },
    ],
    SWE: [
        { r: 0, first: ["David","Jan","Robert","Niklas","Ali","Alexander","Håkan","Simon","Hans","Christer","Tobias","Christian","Michael","Göran","Tommy"], last: ["Gustavsson","Olofsson","Bergström","Petersson","Berglund","Sandberg","Forsberg","Mattsson","Sjöberg","Engström","Fredriksson","Bergman","Ericsson","Eklund","Henriksson","Samuelsson","Lind","Danielsson","Holmberg","Nyström","Nyberg","Lundqvist","Gunnarsson","Söderberg","Lundström","Håkansson","Johnsson","Jakobsson","Sandström","Björk","Nordström","Berggren","Eliasson","Isaksson","Arvidsson","Ohlsson","Fransson","Björklund","Jacobsson","Holmgren","Mårtensson","Sundberg","Åberg","Ström","Hedlund","Wikström","Dahlberg","Hellström","Söderström","Hermansson"] },
    ],
    FIN: [
        { r: 0, first: ["Markus","Tomi","Joonas","Heikki","Juho","Tuomas","Pasi","Harri","Tommi","Lauri","Henri","Tero","Olli","Jaakko","Kimmo"], last: ["Laitinen","Lahtinen","Savolainen","Ojala","Kallio","Leppänen","Koivisto","Hakala","Anttila","Manninen","Pitkänen","Väisänen","Laaksonen","Leinonen","Miettinen","Hiltunen","Laakso","Toivonen","Hirvonen","Aalto","Rantala","Räsänen","Nurmi","Peltonen","Mustonen","Seppälä","Saari","Niemelä","Pulkkinen","Moilanen","Hänninen","Lahti","Koskela","Salmi","Kemppainen","Lappalainen","Kettunen","Ahola","Seppänen","Aho","Kauppinen","Halonen","Partanen","Ikonen","Peltola","Huttunen","Suominen","Pesonen","Mikkonen","Oksanen"] },
    ],
    DEN: [
        { r: 0, first: ["Andreas","Brian","Mathias","John","Jakob","Carsten","Lasse","Torben","Allan","Kenneth","Ali","Jørgen","Kristian","Flemming","Dennis"], last: ["Jacobsen","Holm","Olesen","Frederiksen","Schmidt","Laursen","Henriksen","Eriksen","Clausen","Simonsen","Østergaard","Kristiansen","Vestergaard","Svendsen","Iversen","Kjær","Andreasen","Dahl","Nissen","Nørgaard","Søndergaard","Friis","Jeppesen","Jespersen","Jessen","Frandsen","Jepsen","Mogensen","Bruun","Lauridsen","Winther","Bach","Carlsen","Bertelsen","Toft","Krogh","Lassen","Berg","Brandt","Ravn","Bech","Lind","Christoffersen","Gregersen","Holst","Nygaard","Bang","Johnsen","Juul","Kjeldsen"] },
    ],
    CAN: [
        { r: 0, first: ["Alex","James","Robert","Steve","Matthew","Dave","Nick","Jeff","Tony","Joe","Jonathan","Anthony","Kyle","Sam"], last: ["Jones","Miller","James","Thompson","Joseph","White","Young","King","Lau","Robinson","Reid","Rose","Clarke","Walker","Mann","Davis","Moore","Lewis","Wright","Jackson","Paul","Cheng","John","Green","Saini","Clark","Mitchell","Peters","Kelly","Murphy","Chung","Randhawa"] },
        { r: 2, first: ["Ali"], last: ["Kaur","Wang","Chen","Zhang","Dhillon","Lam","Grewal","Tran","Shah","Leung","Kumar","Cheung","Yang","Huang","Ahmad","Tang","Chow","Park"] },
    ],
    MEX: [
        { r: 0, first: ["David","Cesar","Armando","Martin","Alex","Omar","Alfredo","Edgar","Raul","Jose Luis","Enrique","Ivan","Rafael","Julio","Gabriel"], last: ["Rivera","Romero","Moreno","Ramos","Medina","Alvarez","Herrera","Mendez","Castro","Chavez","Luna","Contreras","Juarez","Salazar","Vargas","Muñoz","Estrada","Ortega","Dominguez","Soto","Guzman","Alvarado","Lara","Espinoza","Vega","Carrillo","Velazquez","Gonzales","Sandoval","Cervantes","Avila","Rios","Valdez","Ibarra","Delgado","Solis","Campos","Acosta","Silva","Santiago","Valenzuela","Cortes","Bautista","Marquez","Santos","Camacho","Rosas","Robles","Fernandez","Miranda"] },
    ],
    RSA: [
        { r: 0, first: ["David","Thabiso","Michael","Lucky","Daniel","Patrick","Joseph","Chris","James","Mandla","Thapelo","Vusi","Sbusiso","Paul","Sanele"], last: ["Jacobs","Naidoo","Williams","Moyo","Baloyi","Govender","Pillay","Sibiya","Chauke","Mazibuko","Van Wyk","Adams","Cele","Mathebula","Molefe","Sibanda","Maluleke","Motaung","Moloi","Abrahams","Davids","Zungu","Precious","Zondi","Hadebe","Vilakazi","Xaba"] },
        { r: 1, first: [], last: ["Louw","Smit","Meyer"] },
        { r: 2, first: [], last: ["Zwane","Ncube","Radebe","Tshabalala","Ntuli","Mthethwa","Nxumalo","Maseko","Mabaso","Ngubane","Ngobeni","Mtshali","Mchunu","Mkhwanazi","Phiri","Mnguni","Mnisi","Dladla","Hlongwane","Nkuna"] },
    ],
    IRL: [
        { r: 0, first: ["Peter","Tom","Pat","Thomas","Robert","Tony","Eoin","Darren","Noel","Declan","Andrew","Anthony","Barry","Jason","Keith"], last: ["Obrien","Smith","Oconnor","Osullivan","Oneill","Flynn","Collins","O Connor","Connolly","Whelan","O Brien","Reilly","Doherty","Duffy","Clarke","Kenny","Brady","O Sullivan","Healy","Keane","Moran","Oreilly","Fitzpatrick","Maher","Hayes","Ward","Roche","Browne","Foley","Mcgrath","Casey","Buckley","Hughes","Hogan","Sweeney","Maguire","Cullen","Delaney","Butler","Smyth","White","Keogh","Egan","Oconnell","Cunningham","Hickey","Lyons","Higgins","Sheridan","Mooney"] },
    ],
    POR: [
        { r: 0, first: ["Vitor","David","Marco","Rafael","Alexandre","Eduardo","Nelson","Ruben","Fábio","Sérgio","Helder","Henrique","Bernardo","Gabriel","Leandro"], last: ["Vieira","Cardoso","Nunes","Duarte","Rocha","Coelho","Reis","Neves","Freitas","Cruz","Cunha","Machado","Pires","Fonseca","Tavares","Barbosa","Lima","Matos","Antunes","Castro","Andrade","Figueiredo","Azevedo","Faria","Lourenço","Barros","Filipe","Morais","Pinheiro","Abreu","Batista","Henriques","Mota","Jesus","Afonso","Simões","Guerreiro","Rosa","Brito","Nogueira","Borges","Melo","Araújo","Esteves","Magalhães","Maia","Baptista","Moura","Neto","Amaral"] },
    ],
    COL: [
        { r: 0, first: ["Jhon","Alexander","Manuel","Alex","Felipe","Jaime","Juan Carlos","Edwin","Jesus","Pedro","Wilson","Victor","Brayan","Cesar","Fabian"], last: ["Alvarez","Herrera","Suarez","Giraldo","Castillo","Arias","Rivera","Cardona","Marin","Zapata","Medina","Osorio","Mendoza","Peña","Parra","Guerrero","Salazar","Mejia","Cardenas","Florez","Jaramillo","Mosquera","Acosta","Londoño","Correa","Reyes","Cruz","Ramos","Molina","Cortes","Ortega","Mora","Escobar","Vasquez","Contreras","Rios","Velasquez","Guzman","Agudelo","Sierra","Rincon","Mendez","Castañeda","Lozano","Silva","Henao","Gonzales","Fernandez","Castaño","Orozco"] },
    ],
    RUS: [
        { r: 0, first: ["Aleksandr","Aleksei","Dmitrii","Evgenii","Maksim","Yurii","Sergey","Vitalii","Andrey","Konstantin","Vyacheslav","Vasilii","Anatolii","Artur","Vlad"], last: ["Magomedov","Aliev","Vasilev","Sergeev","Shevchenko","Mikhailov","Romanov","Kim","Ibragimov","Nikolaev","Stepanov","Akhmedov","Zakharov","Bondarenko","Kovalenko","Semenov","Aleksandr","Kot","Maksimov","Isaev","Kravchenko","Yakovlev","Elena","Aleksandrov","Aleksandrovna","Grigorev","Mamedov","Frolov","Nazarov","Sergeevich","Sergeevna","Aleksandrovich","Borisov","Antonov","Tkachenko","Karimov","Gadzhiev","Yusupov","Kuzmin","Natalya","Sergei","Dmitriev","Tatyana","Medvedev","Abdullaev","Mironov","Tarasov","Zhukov","Kurbanov","Vladimirovich"] },
    ],
    POL: [
        { r: 0, first: ["Daniel","Patryk","Karol","Adrian","Tomek","Janusz","Bartek","Kuba","Jerzy","Wojtek","Dominik","Krystian","Jarosław","Arkadiusz","Roman"], last: ["Szewczyk","Wilk","Stępień","Baran","Marciniak","Duda","Pietrzak","Lis","Kot","Wojciechowski","Kubiak","Kwiatkowski","Mazurek","Bąk","Kozłowski","Włodarczyk","Janik","Kowal","Krupa","Sobczak","Szulc","Michalski","Kołodziej","Marek","Maj","Szymczak","Polak","Nowakowski","Kaźmierczak","Kaczmarczyk","Mucha","Kania","Kowalik","Kozak","Szczepaniak","Wawrzyniak","Nowicki","Mróz","Jarosz","Jaworski","Pawłowski","Błaszczyk","Sowa","Majewski","Markiewicz","Urbaniak","Kruk","Malinowski","Stankiewicz","Olszewski"] },
    ],
    CZE: [
        { r: 0, first: ["Honza","Jirka","Patrik","Vladimír","Dominik","Ondra","Libor","Robert","Stanislav","Matěj","Radim","Ivan","Vojta","Kuba","Jarda"], last: ["Petr","Zeman","Jelínek","Novakova","Růžička","Kolář","Doležal","Čermák","Moravec","Kadlec","Soukup","Musil","Kříž","Malý","Vaněk","Holub","Šimek","Blažek","Kratochvíl","Pavel","Vlček","Polák","Janda","Štěpánek","Šťastný","Valenta","Bartoš","Kopecký","Navrátil","Mareš","Čech","Mašek","Staněk","Mach","Sýkora","Novotna","Kovář","Vacek","Jan","Bláha","Toman","Matoušek","Strnad","Vávra","Beran","Říha","Tichý","Havel","Dostál","Dušek"] },
    ],
    HUN: [
        { r: 0, first: ["Imre","Gergő","Roland","Gergely","Szabolcs","Lajos","Gyula","Ákos","Viktor","Bálint","Miklós","Béla","Mihály","Nagy","Richárd"], last: ["László","Tamás","Gábor","Péter","Zoltán","Balázs","Attila","Sándor","István","Lakatos","Zsolt","Kis","Szilágyi","János","Rácz","Dávid","József","Kocsis","Csaba","Török","Szűcs","Ádám","Ferenc","András","Oláh","Fodor","Magyar","Gál","Fehér","Tibor","Szalai","Máté","Antal","Sipos","Bálint","Pintér","Katona","György","Andrea","Katalin","Gergely","Éva","Király","Imre","Jakab","Boros","Pál","Somogyi","Dániel","Judit"] },
    ],
    URU: [
        { r: 0, first: ["Javier","Miguel","Sergio","Lucas","Rodrigo","Mario","Agustin","Facundo","Leonardo","Roberto"], last: ["Hernandez","Castro","De Los Santos","Moreira","Rivero","Mendez","Sanchez","Morales","Pereyra","Silvera","Silveira","Viera","Pintos","Romero","Ramos","Alvez","Torres","Da Silva","Duarte","Medina","Ramirez","Delgado","Gutierrez","Larrosa","Santos","Benitez","Piriz","Costa","Barboza","Lima"] },
    ],
    ISR: [
        { r: 0, first: ["Mohammad","Michael","Alex","Mohamad","Tal","Amit","Idan","Yuval","Rami","Shay"], last: ["Bar","Tal","Yosef","Mor","Awad","Vaknin","Golan","Hadad","Moshe","Mohammad","Abed","Levin","Amer","Saleh","Azulay","Nassar","Shalom","Edri","Hamdan","Alon","Segal","Salah","Gabay","Hazan","Israel","Elbaz","Aharon","Khateeb","Dayan","Chen"] },
    ],
    IND: [
        { r: 0, first: ["Raju","Anil","Sonu","Mukesh","Dinesh","Pankaj","Suraj","Mahesh","Mohd","Sachin"], last: ["Raj","Roy","Rajput","Kumari","Shaikh","Sahu","Alam","Parmar","Mondal","Pandey","Pal","Shah","Saini","Ram","Jain","Prajapati","Rathod","Tiwari","Soni","Sarkar","Mandal","Malik","Ahmad","Meena","Solanki","Chaudhary","Hussain","Jadhav"] },
        { r: 1, first: [], last: ["Patil","Nayak"] },
    ],
    MAS: [
        { r: 0, first: ["Mohd","Muhammad","Muhd","Mohamad","Abdul","Muhamad","Mohammad"], last: ["Mohamad","Man","Zakaria","Ramli","Mohd","Din","Nizam","Azmi","Sulaiman","Aiman","Firdaus","Rahim","Hakim","Hafiz","Raj","Yee","Ishak","Anuar"] },
        { r: 1, first: ["Wan","Tan","Lee"], last: ["Low","Wan","Leong","Liew","Lai","Ling","Lau","Chai","Loh","Chew","Ooi","Chua"] },
    ],
    INA: [
        { r: 0, first: ["Muhammad","Ahmad","Abdul","Achmad","David","Edy","Ali","Andy","Mas","Benny"], last: ["Tan","Lim","Lie","Sari","Dewi","Lee","Ahmad","Putri","Irawan","Iskandar","Arifin","Prasetyo","Hadi","Purnomo","Wati","Budiman","Lestari","Wahyudi","Chen","Jaya","Yusuf","Hermawan","Anwar","Widodo","Sutanto","Susilo","Muhammad","Maulana","Yanto","Rahman"] },
    ],
    EST: [
        { r: 0, first: ["Alex","Viktor","Tanel","Priit","Mihkel","Marek","Toomas","Madis","Denis","Indrek"], last: ["Olen","Jõgi","Põder","Toom","Kütt","Lepp","Raudsepp","Laur","Raud","Leppik","Männik","Jakobson","Sild","Kallas","Paju","Teder","Lõhmus","Sarapuu","Kuusik","Nõmm","Tamme","Johanson","Lember"] },
        { r: 1, first: [], last: ["Ivanova","Smirnova","Petrova","Kuznetsova","Vassiljeva","Hein","Pavlova"] },
    ],
    MAR: [
        { r: 0, first: [], last: ["Rajawi","Ayoub","Med","Hamza","Raja","Hicham","Malak","Khalid","Fleur","Khadija","Fatima","Amin","Widadi","Mks","Nour","Hamid","Yassine","Rifi","Tanjawi","Agadir"] },
    ],
};
