    e76: [
      '🌧️ Runde {lap}: Jetzt regnet es! Die Piste wird rutschig.',  // claude:1 [-]
      '🌧️ Runde {lap}: Die ersten Tropfen fallen auf die Piste.',  // qwen:1 [-]
      '🌧️ Runde {lap}: Ein plötzlicher Schauer erfasst die Strecke.',  // gemini:1 [-]
      '🌧️ Runde {lap}: Regen setzt ein, und der Kurs verändert sich unter den Rädern.',  // kimi:1 [-]
      '🌧️ Runde {lap}: Der Regen setzt ein, und {leader} muss die Führung auf nassem Asphalt verteidigen.',  // mistral:1 [L]
      '🌧️ {leader} führt weiter, während der Regen einsetzt.',  // chatgpt:2 [L]
      '🌧️ Runde {lap}: Regen setzt ein – {leader} führt, und die Piste wird glatt!',  // claude:5 [L]
      '🌧️ {driver} muss sich nun auf nasser Piste behaupten.',  // qwen:14 [D]
      '🌧️ {leader} führt das Feld durch den einsetzenden Regen.',  // gemini:2 [L]
      '🌧️ Über dem Kurs verdunkelt sich der Himmel, erste Tropfen mischen sich in den Kampf.',  // kimi:2 [-]
      '🌧️ Runde {lap}: Die Bahn wird glatt – {leader} klebt weiter an der Spitze.',  // mistral:2 [L]
      '🌧️ Runde {lap}: Regen setzt ein – die Strecke wird nass.',  // chatgpt:1 [-]
      '🌧️ Runde {lap}: Es regnet! An der Spitze: {leader}.',  // claude:6 [L]
      '🌧️ Runde {lap}: Plötzlicher Wettersturz über der Strecke.',  // qwen:2 [-]
      '🌧️ {driver} spürt die ersten Regentropfen.',  // gemini:13 [D]
      '🌧️ Runde {lap}: Der Asphalt glänzt plötzlich, der Regen ist da.',  // kimi:3 [-]
      '🌧️ In Runde {lap} erreicht der Regen die Strecke, und {leader} führt weiter.',  // mistral:3 [L]
      '🌧️ Runde {lap}: Jetzt kommt der Regen ins Rennen.',  // chatgpt:3 [-]
      '🌧️ Runde {lap}: Nasse Piste, neue Lage – {leader} führt das Feld an.',  // claude:7 [L]
      '🌧️ Runde {lap}: Regenwolken ziehen über dem Kurs auf.',  // qwen:3 [-]
      '🌧️ {leader} führt durch die nassen Runden.',  // gemini:17 [L]
      '🌧️ Nasser Asphalt, grauer Himmel – das Rennen bekommt eine neue Kulisse.',  // kimi:4 [-]
      '🌧️ Runde {lap}: Regentropfen auf den Fernsehkameras – vorn fährt {leader} durch die feuchten Passagen.',  // mistral:4 [L]
      '🌧️ Erste Tropfen fallen – die Bahn wird rutschiger.',  // chatgpt:4 [-]
      '🌧️ Runde {lap}: Regen auf der Strecke, und {leader} liegt vorn – jetzt wird es spannend!',  // claude:8 [L]
      '🌧️ Runde {lap}: Die Bahn wird zunehmend nasser.',  // qwen:4 [-]
      '🌧️ Runde {lap}: {driver} spürt den nassen Gripverlust.',  // gemini:21 [D]
      '🌧️ Runde {lap}: Tropfen schlagen auf den Kurs, der Grip wirkt jetzt kostbarer.',  // kimi:5 [-]
      '🌧️ Runde {lap}: Der Asphalt dunkelt ab, {leader} behält die Nase vorn.',  // mistral:5 [L]
      '🌧️ Runde {lap}: Der Regen erreicht die Strecke.',  // chatgpt:5 [-]
      '🌧️ Runde {lap}: Regen! Die Strecke wird nass, das Feld muss reagieren.',  // claude:2 [-]
      '🌧️ {driver} sieht sich plötzlich mit Nässe konfrontiert.',  // qwen:16 [D]
      '🌧️ {driver} steuert den Wagen durch nasses Terrain.',  // gemini:25 [D]
      '🌧️ Regen! Die Bilder zeigen nasse Stellen, und das Feld stellt sich darauf ein.',  // kimi:6 [-]
      '🌧️ Ab Runde {lap} wird die Piste nass: {leader} bleibt die Referenz an der Spitze.',  // mistral:6 [L]
      '🌧️ Runde {lap}: Nässe kommt auf, das Rennen nimmt eine neue Wendung.',  // chatgpt:7 [-]
      '🌧️ Runde {lap}: Erst ein paar Tropfen, dann mehr – es regnet!',  // claude:3 [-]
      '🌧️ {driver} navigiert durch die einsetzenden Schauer.',  // qwen:18 [D]
      '🌧️ Runde {lap}: {leader} behält im einsetzenden Regen die Führung.',  // gemini:28 [L]
      '🌧️ Runde {lap}: Wassertropfen hängen an den Helmen, der Kurs wird feucht.',  // kimi:7 [-]
      '🌧️ Runde {lap}: Wasser auf der Bahn! {leader} hält die Führung, dahinter wird es rutschig.',  // mistral:7 [L]
      '🌧️ Der Himmel öffnet sich – Regen setzt ein.',  // chatgpt:8 [-]
      '🌧️ Runde {lap}: Wetterumschwung! Das Rennen bekommt eine neue Wendung.',  // claude:4 [-]
      '🌧️ Runde {lap}: Nasse Bedingungen erreichen {driver}.',  // qwen:19 [D]
      '🌧️ Runde {lap}: {driver} kämpft gegen die nassen Bedingungen.',  // gemini:32 [D]
      '🌧️ Nasse Bedingungen auf dem Kurs – das Rennen bekommt einen raueren Anstrich.',  // kimi:8 [-]
      '🌧️ Der Regen erwischt das Feld in Runde {lap}, und vorn führt {leader} durch die Nässe.',  // mistral:8 [L]
      '🌧️ Runde {lap}: Regen mischt das Geschehen auf.',  // chatgpt:9 [-]
      '🌧️ {driver} verliert durch den Regen an Sichtweite.',  // qwen:20 [D]
      '🌧️ Tropfen fallen auf die Visiere, als der Regen beginnt.',  // gemini:3 [-]
      '🌧️ Runde {lap}: Regen im Rennen, und vorne bleibt {leader} vorerst die Referenz.',  // kimi:15 [L]
      '🌧️ Runde {lap}: Regen! Die Bahn wird rutschig, das Feld muss aufpassen.',  // mistral:31 [-]
      '🌧️ {leader} an der Spitze, doch nun wird es nass.',  // chatgpt:6 [L]
      '🌧️ Runde {lap}: Ein Schauer erreicht das Rennareal.',  // qwen:5 [-]
      '🌧️ {driver} navigiert durch den plötzlichen Regenschauer.',  // gemini:35 [D]
      '🌧️ Runde {lap}: Der Himmel öffnet sich, der Grand Prix bekommt nasse Füße.',  // kimi:9 [-]
      '🌧️ Runde {lap}: Die Fernsehbilder lügen nicht – die Bahn ist nass, {leader} führt.',  // mistral:9 [L]
      '🌧️ Runde {lap}: Jetzt wird die Bahn nass.',  // chatgpt:11 [-]
      '🌧️ Runde {lap}: {driver} kämpft mit der glatten Fahrbahn.',  // qwen:21 [D]
      '🌧️ Die Sicht wird schlechter, da Regen einsetzt.',  // gemini:4 [-]
      '🌧️ Runde {lap}: {driver} nimmt die ersten Tropfen zur Kenntnis, die Spur wird feucht.',  // kimi:16 [D]
      '🌧️ Ab Runde {lap} heißt es volle Konzentration auf nasser Strecke.',  // mistral:32 [-]
      '🌧️ {leader} führt, während die Strecke zunehmend nass wird.',  // chatgpt:10 [L]
      '🌧️ Runde {lap}: Nässe macht sich auf dem Asphalt breit.',  // qwen:6 [-]
      '🌧️ Runde {lap}: {driver} trotzt dem nassen Wetter.',  // gemini:39 [D]
      '🌧️ Plötzlich spritzt es an der Strecke, und jeder Meter wirkt schwerer.',  // kimi:10 [-]
      '🌧️ Nasse Bahn ab Runde {lap}: {driver} muss nun mit weniger Haftung klarkommen.',  // mistral:10 [D]
      '🌧️ Regen kommt auf – die Bedingungen ändern sich.',  // chatgpt:12 [-]
      '🌧️ {driver} spürt den Wetterumschwung im Cockpit.',  // qwen:22 [D]
      '🌧️ Runde {lap}: Plötzlich fängt es an zu regnen.',  // gemini:5 [-]
      '🌧️ Runde {lap}: Über der Spitze um {leader} liegt Regenluft, der Kurs glänzt bereits nass.',  // kimi:18 [L]
      '🌧️ Runde {lap}: Das Wetter dreht, die Piste wird nass.',  // mistral:33 [-]
      '🌧️ {leader} bleibt vorn, doch der Regen ist da.',  // chatgpt:14 [L]
      '🌧️ Runde {lap}: Der Himmel öffnet sich über der Piste.',  // qwen:7 [-]
      '🌧️ Wasser auf dem Asphalt signalisiert den Regeneinbruch.',  // gemini:6 [-]
      '🌧️ {leader} bleibt vorn, doch Runde {lap} bringt plötzlich Regen auf die Bahn.',  // kimi:19 [L]
      '🌧️ Runde {lap}: {leader} hält die Spitze, während die Strecke glänzend wird.',  // mistral:12 [L]
      '🌧️ Runde {lap}: Nasse Fahrbahn kündigt sich an.',  // chatgpt:13 [-]
      '🌧️ {driver} findet auf der nassen Piste weniger Grip.',  // qwen:24 [D]
      '🌧️ Dunkle Wolken bringen Regen über die Strecke.',  // gemini:8 [-]
      '🌧️ Runde {lap}: Nasse Fahrbahn, dicker Himmel – {leader} führt in eine veränderte Szene.',  // kimi:20 [L]
      '🌧️ In Runde {lap} erfasst der Regen die Bahn – jetzt ist Vorsicht angesagt.',  // mistral:34 [-]
      '🌧️ {leader} führt weiter, jetzt unter nassen Bedingungen.',  // chatgpt:18 [L]
      '🌧️ Runde {lap}: Sichtweite nimmt durch einsetzenden Regen ab.',  // qwen:8 [-]
      '🌧️ Runde {lap}: Nässe überrascht die Piloten.',  // gemini:9 [-]
      '🌧️ Die Kamera fängt Tropfen ein: Runde {lap}, Regen, und {leader} weiter an der Spitze.',  // kimi:21 [L]
      '🌧️ Runde {lap}: Die Strecke verändert sich, {leader} bleibt vorne dran.',  // mistral:13 [L]
      '🌧️ Runde {lap}: Der Regen setzt ein und verändert das Bild.',  // chatgpt:15 [-]
      '🌧️ Runde {lap}: {driver} wird von den Tropfen überrascht.',  // qwen:25 [D]
      '🌧️ Plötzlicher Niederschlag verändert die Bedingungen.',  // gemini:11 [-]
      '🌧️ Runde {lap}: {driver} jagt durch feine Gischt, der Regen kommt nun zum Rennen.',  // kimi:22 [D]
      '🌧️ Runde {lap}: Die Kameras an der Strecke bekommen nasse Objektive.',  // mistral:35 [-]
      '🌧️ {leader} an der Spitze, während Regen einsetzt.',  // chatgpt:22 [L]
      '🌧️ Runde {lap}: Feuchte Konditionen verändern die Strecke.',  // qwen:9 [-]
      '🌧️ Runde {lap}: Regen setzt ein und macht die Fahrbahn nass.',  // gemini:12 [-]
      '🌧️ Runde {lap}: Regentropfen auf der Strecke, {driver} sucht nun den richtigen Rhythmus.',  // kimi:23 [D]
      '🌧️ Runde {lap}: Wetterwechsel! {leader} führt das Feld durch die nassen Kurven.',  // mistral:14 [L]
      '🌧️ Nun wird es nass auf der Strecke.',  // chatgpt:16 [-]
      '🌧️ {driver} muss das Tempo der Nässe anpassen.',  // qwen:26 [D]
      '🌧️ Gischt steigt auf, da es zu regnen beginnt.',  // gemini:14 [-]
      '🌧️ Das Funkeln auf dem Asphalt sagt alles: Runde {lap} wird nass, {leader} steht vorne.',  // kimi:24 [L]
      '🌧️ Runde {lap}: Wasser auf dem Asphalt – das Rennen bekommt eine neue Note.',  // mistral:36 [-]
      '🌧️ {leader} bleibt Spitzenreiter, während Regen einsetzt.',  // chatgpt:30 [L]
      '🌧️ Runde {lap}: Wasserfilme bilden sich auf der Fahrbahn.',  // qwen:10 [-]
      '🌧️ Runde {lap}: Das Wetter schlägt um und Regen setzt ein.',  // gemini:15 [-]
      '🌧️ Runde {lap}: Regen bricht herein, während {leader} das Feld anführt.',  // kimi:26 [L]
      '🌧️ In Runde {lap} dreht das Wetter, {leader} bleibt in Führung – die Bahn wird feucht.',  // mistral:15 [L]
      '🌧️ Runde {lap}: Regen zieht auf und erreicht die Bahn.',  // chatgpt:17 [-]
      '🌧️ Runde {lap}: {driver} tastet sich an die nassen Grenzen heran.',  // qwen:29 [D]
      '🌧️ Die Piloten kämpfen mit plötzlich nasser Strecke.',  // gemini:19 [-]
      '🌧️ Der Himmel schaltet auf grau: Runde {lap}, Regen, und {leader} führt das Feld an.',  // kimi:27 [L]
      '🌧️ Der Himmel hält Wort: die Bahn wird nass, und das Rennen wechselt das Gesicht.',  // mistral:37 [-]
      '🌧️ {leader} führt weiter, nun kommt Regen auf.',  // chatgpt:34 [L]
      '🌧️ Runde {lap}: Ein Regenschauer überzieht den Kurs.',  // qwen:11 [-]
      '🌧️ Ein Regenschauer zieht über den Kurs.',  // gemini:20 [-]
      '🌧️ Runde {lap}: Tropfen treffen die Visiere, und {leader} führt durch die neue Szene.',  // kimi:28 [L]
      '🌧️ Runde {lap}: Der Regen ist da – {driver} muss sich an die neue Bahn gewöhnen.',  // mistral:16 [D]
      '🌧️ Runde {lap}: Die ersten Regentropfen sind da.',  // chatgpt:19 [-]
      '🌧️ {driver} sieht sich mit rutschigem Untergrund konfrontiert.',  // qwen:30 [D]
      '🌧️ Wasserflecken auf dem Visier kündigen Regen an.',  // gemini:22 [-]
      '🌧️ Auf dem Bildschirm wird es nass: Runde {lap} stellt {driver} vor ein anderes Bild.',  // kimi:29 [D]
      '🌧️ Regen! Die Tribünen öffnen die Regencapes, die Piste glänzt im Licht.',  // mistral:38 [-]
      '🌧️ {leader} liegt vorn, während die Bahn nasser wird.',  // chatgpt:38 [L]
      '🌧️ Runde {lap}: Die Witterung schlägt augenblicklich um.',  // qwen:12 [-]
      '🌧️ Runde {lap}: Der Regen beginnt im laufenden Rennen.',  // gemini:23 [-]
      '🌧️ Runde {lap}: {driver} blickt in einen grauen Horizont, die Fahrbahn glänzt schon.',  // kimi:30 [D]
      '🌧️ Runde {lap}: Es wird nass, und {leader} gibt an der Spitze den Takt an.',  // mistral:17 [L]
      '🌧️ Regen setzt ein – auf der Strecke wird es glatt.',  // chatgpt:20 [-]
      '🌧️ Runde {lap}: {driver} durchfährt eine nasse Passage.',  // qwen:31 [D]
      '🌧️ Rutschige Passagen entstehen durch einsetzenden Regen.',  // gemini:24 [-]
      '🌧️ Runde {lap}: Aus der Ferne zieht Regen über den Kurs, vorne ist es {leader}.',  // kimi:32 [L]
      '🌧️ Es regnet – ein Fehler auf dem nassen Asphalt bleibt nicht unbestraft.',  // mistral:39 [-]
      '🌧️ Runde {lap}: Die Fahrbahn bekommt die ersten nassen Stellen.',  // chatgpt:21 [-]
      '🌧️ {driver} muss bei einsetzendem Regen die Linie finden.',  // qwen:32 [D]
      '🌧️ Der Zustand der Strecke ändert sich durch Regen.',  // gemini:27 [-]
      '🌧️ Jetzt hängt Wasser in der Luft: Runde {lap}, nasse Strecke, {leader} an der Spitze.',  // kimi:33 [L]
      '🌧️ Regen in Runde {lap}: {leader} fährt vorn, während die Piste das Licht reflektiert.',  // mistral:19 [L]
      '🌧️ Runde {lap}: Nässe kommt ins Spiel.',  // chatgpt:23 [-]
      '🌧️ Runde {lap}: {driver} spürt den nachlassenden Grip durch Nässe.',  // qwen:33 [D]
      '🌧️ Grauer Himmel und Regen prägen das Bild.',  // gemini:29 [-]
      '🌧️ Runde {lap}: Es regnet, und selbst {leader} bekommt die neue Härte zu spüren.',  // kimi:34 [L]
      '🌧️ Regen auf der Piste – Konzentration ist jetzt das A und O.',  // mistral:40 [-]
      '🌧️ Der Regen ist da – die Strecke wird feucht.',  // chatgpt:24 [-]
      '🌧️ Runde {lap}: {driver} bewegt sich auf glatter werdendem Asphalt.',  // qwen:35 [D]
      '🌧️ Runde {lap}: Schleudern auf nasser Piste droht.',  // gemini:30 [-]
      '🌧️ Runde {lap}: Der Regen trifft den Asphalt, {driver} trifft auf eine andere Rennphase.',  // kimi:35 [D]
      '🌧️ Runde {lap}: Der Himmel öffnet sich, und {driver} muss die nassen Bremszonen meistern.',  // mistral:20 [D]
      '🌧️ Runde {lap}: Jetzt verändert der Regen die Bedingungen.',  // chatgpt:25 [-]
      '🌧️ {driver} begegnet auf der Piste zunehmendem Wasserrisiko.',  // qwen:36 [D]
      '🌧️ Regen setzt ein und fordert die Fahrer.',  // gemini:31 [-]
      '🌧️ Regen auf dem Kurs in Runde {lap} – für {driver} beginnt der heikle Teil des Tages.',  // kimi:36 [D]
      '🌧️ Runde {lap}: Wasser von oben, und {leader} behält oben die Übersicht.',  // mistral:21 [L]
      '🌧️ Runde {lap}: Regen erreicht die Strecke, die Bahn wird nass.',  // chatgpt:27 [-]
      '🌧️ Runde {lap}: Nasser Asphalt fordert alle heraus.',  // qwen:13 [-]
      '🌧️ Feuchtigkeit auf dem Asphalt überrascht das Feld.',  // gemini:33 [-]
      '🌧️ Runde {lap}: Die Spur verliert ihren trockenen Glanz, und {leader} führt ins Ungewisse.',  // kimi:37 [L]
      '🌧️ Runde {lap}: Die Piste verlangt Feingefühl, {leader} liefert es an der Spitze.',  // mistral:22 [L]
      '🌧️ Auf der Strecke setzt Regen ein.',  // chatgpt:28 [-]
      '🌧️ Runde {lap}: {driver} muss die Fahrweise dem Regen angleichen.',  // qwen:37 [D]
      '🌧️ Runde {lap}: Der Regen setzt dem Asphalt zu.',  // gemini:34 [-]
      '🌧️ Mit Runde {lap} kommt der Regen, und {leader} führt das Feld in die nasse Phase.',  // kimi:38 [L]
      '🌧️ Runde {lap}: Regen! {leader} führt – eine Bilderbuchkulisse fürs Fernsehen.',  // mistral:23 [L]
      '🌧️ Runde {lap}: Die Bedingungen werden mit dem Regen nasser.',  // chatgpt:29 [-]
      '🌧️ {driver} erlebt einen plötzlichen Wettereinbruch auf der Strecke.',  // qwen:38 [D]
      '🌧️ Nasser Untergrund verändert das Renngeschehen.',  // gemini:36 [-]
      '🌧️ Runde {lap}: Regen zieht auf, die Kulisse passt zum harten Rennen.',  // kimi:11 [-]
      '🌧️ Runde {lap}: Nasser Asphalt – {leader} hat die Führung fest im Griff.',  // mistral:24 [L]
      '🌧️ Runde {lap}: Der Regen beginnt und die Bahn wird rutschig.',  // chatgpt:31 [-]
      '🌧️ Runde {lap}: {driver} behält die nasse Piste im Blick.',  // qwen:39 [D]
      '🌧️ Wasser sammelt sich auf der Ideallinie.',  // gemini:40 [-]
      '🌧️ Runde {lap}: Die Strecke spricht von Regen, {leader} zeigt die Richtung.',  // kimi:39 [L]
      '🌧️ {leader} führt weiterhin, doch die Bahn wird mit jedem Meter nasser.',  // mistral:26 [L]
      '🌧️ Feuchtigkeit kommt auf die Strecke – der Regen setzt ein.',  // chatgpt:32 [-]
      '🌧️ Feuchter Asphalt und graues Licht – die Sache wird heikel.',  // kimi:12 [-]
      '🌧️ Nasse Bahn, glatte Kurven – {leader} bleibt trotzdem vorne.',  // mistral:27 [L]
      '🌧️ Runde {lap}: Regen macht sich auf der Bahn bemerkbar.',  // chatgpt:33 [-]
      '🌧️ Runde {lap}: Die Bahn ist jetzt nass, und das TV-Bild zeigt die Regentropfen.',  // kimi:13 [-]
      '🌧️ Es wird nass hier: {leader} führt, und die Strecke wird zur Prüfung.',  // mistral:28 [L]
      '🌧️ Runde {lap}: Die Strecke wird nass, der Regen ist angekommen.',  // chatgpt:35 [-]
      '🌧️ Auf glattem Asphalt führt weiterhin {leader}.',  // mistral:29 [L]
      '🌧️ Regen fällt auf die Strecke.',  // chatgpt:36 [-]
      '🌧️ Regenschirme an den Tribünen: {leader} fährt weiter an der Spitze.',  // mistral:30 [L]
      '🌧️ Runde {lap}: Nun setzt der Regen spürbar ein.',  // chatgpt:37 [-]
      '🌧️ Runde {lap}: Regen verändert die Bedingungen auf der Strecke.',  // chatgpt:39 [-]
      '🌧️ Jetzt ist der Regen auf der Strecke angekommen.'  // chatgpt:40 [-]
    ]
